# Generated by Django 4.0 on 2022-11-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='notebook_file',
            field=models.FileField(blank=True, null=True, upload_to='data/'),
        ),
    ]
