# Generated by Django 4.0 on 2022-11-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_run_notebook_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='analyst_id',
            field=models.PositiveIntegerField(default=0, verbose_name='analyst'),
        ),
    ]
