# Generated by Django 4.0 on 2022-11-21 07:29

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_run_analyst_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='RUN_NAME', max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
    ]
