# Generated by Django 4.0 on 2022-11-21 07:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_metric'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('metric_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.metric')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.run')),
            ],
        ),
    ]
