# Generated by Django 3.2.8 on 2022-11-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_runmetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='project_id',
            field=models.PositiveIntegerField(default=0, verbose_name='analyst'),
        ),
    ]
