# Generated by Django 3.2.8 on 2022-11-21 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_project_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(default='MISSING', max_length=40, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
